module.exports = {
  "code": 0,
  "message": "成功请求",
  "data": [{
    "lanmu_id": 0,
    "lanmu_name": "头条",
    "lanmu_order": 0,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=0"
  }, {
    "lanmu_id": 32,
    "lanmu_name": "合肥",
    "lanmu_order": 1,
    "lanmu_menu": 1,
    "lanmu_custom": 1,
    "lanmu_json": "/V2/news/list.html?chid=32"
  }, {
    "lanmu_id": 59,
    "lanmu_name": "时政",
    "lanmu_order": 2,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=59"
  }, {
    "lanmu_id": 61,
    "lanmu_name": "热点",
    "lanmu_order": 3,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=61"
  }, {
    "lanmu_id": 13,
    "lanmu_name": "图片",
    "lanmu_order": 4,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=13"
  }, {
    "lanmu_id": 30,
    "lanmu_name": "视频",
    "lanmu_order": 5,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=30"
  }, {
    "lanmu_id": 2,
    "lanmu_name": "民生",
    "lanmu_order": 6,
    "lanmu_menu": 1,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=2"
  }, {
    "lanmu_id": 70,
    "lanmu_name": "原创",
    "lanmu_order": 7,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=70"
  }, {
    "lanmu_id": 111,
    "lanmu_name": "品读",
    "lanmu_order": 8,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=111"
  }, {
    "lanmu_id": 12,
    "lanmu_name": "专题",
    "lanmu_order": 9,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=12"
  }, {
    "lanmu_id": 60,
    "lanmu_name": "锐评",
    "lanmu_order": 10,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=60"
  }, {
    "lanmu_id": 62,
    "lanmu_name": "好人",
    "lanmu_order": 11,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=62"
  }, {
    "lanmu_id": 10,
    "lanmu_name": "汽车",
    "lanmu_order": 12,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=10"
  }, {
    "lanmu_id": 9,
    "lanmu_name": "教育",
    "lanmu_order": 13,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=9"
  }, {
    "lanmu_id": 8,
    "lanmu_name": "旅游",
    "lanmu_order": 14,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=8"
  }, {
    "lanmu_id": 11,
    "lanmu_name": "房产",
    "lanmu_order": 15,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=11"
  }, {
    "lanmu_id": 48,
    "lanmu_name": "徽商",
    "lanmu_order": 16,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=48"
  }, {
    "lanmu_id": 112,
    "lanmu_name": "理论",
    "lanmu_order": 17,
    "lanmu_menu": 0,
    "lanmu_custom": 0,
    "lanmu_json": "/V2/news/list.html?chid=112"
  }],
  "updateDime": 1471398874
}